Name:           ros-jade-schunk-canopen-driver
Version:        1.0.6
Release:        0%{?dist}
Summary:        ROS schunk_canopen_driver package

Group:          Development/Libraries
License:        FZI all rights reserved
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-actionlib
Requires:       ros-jade-control-msgs
Requires:       ros-jade-controller-manager
Requires:       ros-jade-fzi-icl-can
Requires:       ros-jade-fzi-icl-core
Requires:       ros-jade-hardware-interface
Requires:       ros-jade-joint-limits-interface
Requires:       ros-jade-message-runtime
Requires:       ros-jade-robot-state-publisher
Requires:       ros-jade-ros-controllers
Requires:       ros-jade-roscpp
Requires:       ros-jade-sensor-msgs
Requires:       ros-jade-std-msgs
Requires:       ros-jade-std-srvs
Requires:       ros-jade-urdf
Requires:       ros-jade-xacro
BuildRequires:  ros-jade-actionlib
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-control-msgs
BuildRequires:  ros-jade-controller-manager
BuildRequires:  ros-jade-fzi-icl-can
BuildRequires:  ros-jade-fzi-icl-core
BuildRequires:  ros-jade-hardware-interface
BuildRequires:  ros-jade-joint-limits-interface
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-sensor-msgs
BuildRequires:  ros-jade-std-msgs
BuildRequires:  ros-jade-std-srvs
BuildRequires:  ros-jade-urdf

%description
The schunk_canopen_driver package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Thu May 19 2016 Georg Heppner <heppner@fzi.de> - 1.0.6-0
- Autogenerated by Bloom

